fragment HeroBlock on HeroBlock {
  blockType
  title
  subtitle
  content
  image {
    relationTo
      value {
        ... on Image {
          ...Image
        }
        ... on SVG {
          ...SVG
        }
      }
  }
  buttons {
    ...Button
  }
  layout
  splitRatio
  mediaPosition
  mediaOrder
  overlayOpacity
  textAlignment
  minHeight
}