fragment HeroBlock on HeroBlock {
  blockType
  title
  subtitle
  content
  image {
    ...Media
  }
  buttons {
    ...Button
  }
  layout
  splitRatio
  mediaPosition
  mediaOrder
  overlayOpacity
  textAlignment
  minHeight
}