query GetPage($slug: String!) {
  Pages(limit: 1, where: { slug: { equals: $slug } }) {
    docs {
      id
      title
      slug
      meta {
        title
        description
        image {
          ...SeoImage
        }
      }
      layout {
        ...GridBlock
        ...HeroBlock
        ...TextBlock
      }
    }
  }
}